import React, { createContext, useState, useEffect } from "react";
export const TeacherContext = createContext();
export const TeacherProvider = ({ children }) => {
  const [teachers, setTeachers] = useState([
    {
      id: "#1",
      name: "Dimitres Viga",
      data: "March 25, 2021",
      parent: "Anna Viga",
      city: "New York",
      subject: "Mathematics",
      email: "dimitres@gmail.com",
      phone: "123-456-7890",
      about: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      education: "History Major, University Akademi Historia",
      expertise: "World History, Philosophy, Prehistoric, Culture, Ancient",
    },
    {
      id: "#2",
      name: "Tom Housenburg",
      data: "April 10, 2021",
      parent: "James Housenburg",
      city: "Los Angeles",
      subject: "Science",
      email: "tom@gmail.com",
      phone: "987-654-3210",
      about: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      education: "History Major, University Akademi Historia",
      expertise: "World History, Philosophy, Prehistoric, Culture, Ancient",
    },
    {
      id: "#3",
      name: "Dana Benevista",
      data: "June 15, 2021",
      parent: "Maria Benevista",
      city: "Chicago",
      subject: "Art",
      email: "dana@gmail.com",
      phone: "555-555-5555",
      about: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      education: "History Major, University Akademi Historia",
      expertise: "World History, Philosophy, Prehistoric, Culture, Ancient",
    },
    {
      id: "#4",
      name: "Salvadore",
      data: "July 20, 2021",
      parent: "Lucia Morbeau",
      city: "Miami",
      subject: "Biology",
      email: "salvadore@gmail.com",
      phone: "111-222-3333",
      about: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      education: "History Major, University Akademi Historia",
      expertise: "World History, Philosophy, Prehistoric, Culture, Ancient",
    },
    {
      id: "#5",
      name: "Maria Historia",
      data: "August 5, 2021",
      parent: "Gabriel Historia",
      city: "Houston",
      subject: "History",
      email: "maria@gmail.com",
      phone: "444-444-4444",
      about: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      education: "History Major, University Akademi Historia",
      expertise: "World History, Philosophy, Prehistoric, Culture, Ancient",
    },
    {
      id: "#6",
      name: "Jack Sally",
      data: "September 15, 2021",
      parent: "Laura Sally",
      city: "Phoenix",
      subject: "Physics",
      email: "jack@gmail.com",
      phone: "777-777-7777",
      about: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      education: "History Major, University Akademi Historia",
      expertise: "World History, Philosophy, Prehistoric, Culture, Ancient",
    },
    {
      id: "#7",
      name: "Lula Beatrice",
      data: "October 25, 2021",
      parent: "Sandra Beatrice",
      city: "Philadelphia",
      subject: "Algorithm",
      email: "lula@gmail.com",
      phone: "888-888-8888",
      about: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      education: "History Major, University Akademi Historia",
      expertise: "World History, Philosophy, Prehistoric, Culture, Ancient",
    },
    {
      id: "#8",
      name: "Nella Vita",
      data: "November 10, 2021",
      parent: "Rosa Vita",
      city: "San Antonio",
      subject: "English",
      email: "nella@gmail.com",
      phone: "999-999-9999",
      about: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      education: "History Major, University Akademi Historia",
      expertise: "World History, Philosophy, Prehistoric, Culture, Ancient",
    },
    {
      id: "#9",
      name: "Nadia Laravela",
      data: "December 1, 2021",
      parent: "Mark Laravela",
      city: "San Diego",
      subject: "Programming",
      email: "nadia@gmail.com",
      phone: "000-000-0000",
      about: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      education: "History Major, University Akademi Historia",
      expertise: "World History, Philosophy, Prehistoric, Culture, Ancient",
    },
    {
      id: "#10",
      name: "Dakota Farral",
      data: "January 20, 2022",
      parent: "Evan Farral",
      city: "Dallas",
      subject: "Science",
      email: "dakota@gmail.com",
      phone: "123-456-7890",
      about: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      education: "History Major, University Akademi Historia",
      expertise: "World History, Philosophy, Prehistoric, Culture, Ancient",
    },
    {
      id: "#11",
      name: "Miranda Adila",
      data: "February 15, 2022",
      parent: "Chris Adila",
      city: "San Jose",
      subject: "Art",
      email: "miranda@gmail.com",
      phone: "987-654-3210",
      about: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      education: "History Major, University Akademi Historia",
      expertise: "World History, Philosophy, Prehistoric, Culture, Ancient",
    },
    {
      id: "#12",
      name: "Indiana Barker",
      data: "March 25, 2022",
      parent: "Paul Barker",
      city: "Austin",
      subject: "Biology",
      email: "indiana@gmail.com",
      phone: "555-555-5555",
      about: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      education: "History Major, University Akademi Historia",
      expertise: "World History, Philosophy, Prehistoric, Culture, Ancient",
    },
  ]);
  useEffect(() => {
    const storedTeachers = window.localStorage.getItem('teachers');
    if (storedTeachers && storedTeachers != "undefined") {
      setTeachers(JSON.parse(storedTeachers));
    }
  }, []);
  return (
    <TeacherContext.Provider value={{ teachers, setTeachers }}>
      {children}
    </TeacherContext.Provider>
  );
};
